// <auto-generated />
using System;
using Dal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(PtachiyaContext))]
    partial class PtachiyaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dal.Models.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FormLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KindergartenId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ChildId")
                        .HasName("PK__Children__BEFA0716585D1C92");

                    b.HasIndex("KindergartenId");

                    b.HasIndex("PaymentId");

                    b.HasIndex(new[] { "IdNumber" }, "UQ__Children__62DF80332B6EC341")
                        .IsUnique();

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Dal.Models.Customer", b =>
                {
                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Dal.Models.Form", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime");

                    b.HasKey("FormId")
                        .HasName("PK__Forms__FB05B7DD3B2B1448");

                    b.HasIndex("ChildId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Dal.Models.Kindergarten", b =>
                {
                    b.Property<int>("KindergartenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KindergartenId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KindergartenId")
                        .HasName("PK__Kinderga__2B06D7BC1EB3F444");

                    b.HasIndex(new[] { "Code" }, "UQ__Kinderga__A25C5AA7B71BED89")
                        .IsUnique();

                    b.ToTable("Kindergartens");
                });

            modelBuilder.Entity("Dal.Models.Order", b =>
                {
                    b.Property<int?>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime")
                        .HasColumnName("order_date");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Dal.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A389869C495");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Dal.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C0814D012");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4E7221715")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dal.Models.Child", b =>
                {
                    b.HasOne("Dal.Models.Kindergarten", "Kindergarten")
                        .WithMany("Children")
                        .HasForeignKey("KindergartenId")
                        .IsRequired()
                        .HasConstraintName("FK__Children__Kinder__52593CB8");

                    b.HasOne("Dal.Models.Payment", "Payment")
                        .WithMany("Children")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_Children_Payments");

                    b.Navigation("Kindergarten");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Dal.Models.Form", b =>
                {
                    b.HasOne("Dal.Models.Child", "Child")
                        .WithMany("Forms")
                        .HasForeignKey("ChildId")
                        .IsRequired()
                        .HasConstraintName("FK__Forms__ChildId__59063A47");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Dal.Models.Child", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("Dal.Models.Kindergarten", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Dal.Models.Payment", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
